# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "0clmdzxw0kvv0xnza198xg1lmzz0061j6y173018gqgwqhx6cfim";
    x86_64-linux = "1vh4qfrv6wx9wkchh8q1jncag8pvilwpsb1cfm4qvraqrwgwn461";
    x86_64-darwin = "0ddcipvm4jn254rrhavq0z1dbqkn606awy3sky9ic34b3f124y8x";
  };

  urlMap = {
    i686-linux = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.25/foo_1.0.25_linux_386.zip";
    x86_64-linux = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.25/foo_1.0.25_linux_amd64.zip";
    x86_64-darwin = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.25/foo_1.0.25_darwin_amd64.zip";
  };
in pkgs.stdenv.mkDerivation {
  pname = "test";
  version = "1.0.25";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./moises $out/bin/moises
  '';

  system = system;

  meta = with lib; {
    description = "a test";
    homepage = "https://test";
    license = licenses.mit;

    platforms = [
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
