# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "01vn19bijxqbnxh0fj91i8wxkgwlgihwghxg4i9x2nxqqmliyzrb";
    x86_64-linux = "05mvka1g2n7imncq8k1wdsgrb6pw48akarm5wyy0wzj543bayp1y";
    x86_64-darwin = "1gn0rkd4qr03mjza7bvaljdizf2nxw1awvd4ds3bxqjxwzhnv7yb";
  };

  urlMap = {
    i686-linux = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.27/foo_1.0.27_linux_386.zip";
    x86_64-linux = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.27/foo_1.0.27_linux_amd64.zip";
    x86_64-darwin = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.27/foo_1.0.27_darwin_amd64.zip";
  };
in pkgs.stdenv.mkDerivation {
  pname = "test";
  version = "1.0.27";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./moises $out/bin/moises
  '';

  system = system;

  meta = with lib; {
    description = "a test";
    homepage = "https://test";
    license = licenses.mit;

    platforms = [
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
