# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "03djgg7z0a7qgr2ghb5l1jki28q03356r80mhqi3r109hx35b4cg";
    x86_64-linux = "1a2ibzym0hcnyacp7g1cy5d92li4i4vbfha7nhndfr55h39dradv";
    x86_64-darwin = "085fzmqrkz9qbh1wp3lv9742r6ca5i6zsgv1v8d9dma72456a77x";
  };

  urlMap = {
    i686-linux = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.26/foo_1.0.26_linux_386.zip";
    x86_64-linux = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.26/foo_1.0.26_linux_amd64.zip";
    x86_64-darwin = "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.26/foo_1.0.26_darwin_amd64.zip";
  };
in pkgs.stdenv.mkDerivation {
  pname = "test";
  version = "1.0.26";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./moises $out/bin/moises
  '';

  system = system;

  meta = with lib; {
    description = "a test";
    homepage = "https://test";
    license = licenses.mit;

    platforms = [
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
